[package]
name = "ratatui-macros"
version = "0.2.4"
edition = "2021"
authors = ["Dheepak Krishnamurthy"]
description = "Macros for Ratatui"
license = "MIT" # or any other appropriate license
repository = "https://github.com/ratatui-org/ratatui-macros"
documentation = "https://docs.rs/ratatui-macros"
keywords = ["ratatui", "macros", "tui", "ui"]
categories = ["tui", "macro"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# requires alpha version of ratatui for the Into<Style> changes
ratatui = "0.27.0-alpha.5"
ratatui-macros-derive = { version = "0.1.0", path = "ratatui-macros-derive" }

[dev-dependencies]
trybuild = { version = "1.0.93", features = ["diff"] }
cargo-husky = { version = "1.5.0", features = ["user-hooks"] }



