[package]
name = "ratatui-macros"
version = "0.2.4"
edition = "2021"
authors = ["Dheepak Krishnamurthy"]
description = "Macros for Ratatui"
license = "MIT" # or any other appropriate license
repository = "https://github.com/kdheepak/ratatui-macros"
documentation = "https://docs.rs/ratatui-macros"
keywords = ["ratatui", "macros", "tui", "ui"]
categories = ["tui", "macro"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# requires alpha version of ratatui for the Into<Style> changes
ratatui = "0.26.2-alpha.0"

[dev-dependencies]
trybuild = { version = "1.0.88", features = ["diff"] }
cargo-husky = { version = "1.5.0", features = ["user-hooks"] }



